name: First Workflow

on:
  push:  
  workflow_dispatch:

jobs:
  helloworld:
    needs: usingactionjob
    runs-on: ubuntu-latest
    steps:
      - run: echo hello world
      - run: tree
        name: Tree Before Checkout
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Tree After Checkout
        run: tree
      - run: cat README.md
  usingactionjob:
    runs-on: ubuntu-latest
    steps:
      - uses: nicruo/novemberaction@v1
      - run: echo 'Hello world from summary' >> $GITHUB_STEP_SUMMARY
