name: First Workflow

on:
  push:  
  workflow_dispatch:

jobs:
  usingactionjob:
    runs-on: ubuntu-latest
    steps:
      - uses: nicruo/novemberaction@v1
      - run: echo 'Hello world from summary' >> $GITHUB_STEP_SUMMARY
      
  helloworld:
    needs: usingactionjob
    runs-on: ubuntu-latest
    steps:
      - run: echo hello world
      - run: tree
        name: Tree Before Checkout
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Tree After Checkout
        run: tree
      - run: cat README.md
  
  jobA:
    runs-on: windows-latest
    needs: helloworld
    steps:
      - run: pwd
  jobB:
    runs-on: windows-latest
    needs: helloworld
    steps:
      - run: pwd
  jobC:
    runs-on: windows-latest
    needs: jobB
    steps:
      - run: pwd
